### ISSUE TITLE
Elasticsearch version info?

### ISSUE THREAD

**Issue by sckott** [metacran/pkgsearch#12]
just trying to connect from the `elastic` R pkg - part of the internals is sorting out which Elasticsearch version the user is connected to - because many Elasticsearch APIs depend on the version running. I ping the base url which is usually the base url (e.g. on localhost http://localhost:9200/)

```json
{
  "name": "nSEljzO",
  "cluster_name": "elasticsearch",
  "cluster_uuid": "8ur756SZQ5W-uWv47VALcA",
  "version": {
    "number": "6.4.0",
    "build_flavor": "default",
    "build_type": "tar",
    "build_hash": "595516e",
    "build_date": "2018-08-17T23:18:47.308994Z",
    "build_snapshot": false,
    "lucene_version": "7.4.0",
    "minimum_wire_compatibility_version": "5.6.0",
    "minimum_index_compatibility_version": "5.0.0"
  },
  "tagline": "You Know, for Search"
}
```

do you have anything like this exposed in the API?  wondering how common this is if there's no ES version available 🤔

**Comment by gaborcsardi** [comment]
I don't have all the API available, just some search entry points that I need.  I can make the root available, if that' good.  

```
{
"status": 200,
"name": "Overmind",
"version": {
"number": "1.3.9",
"build_hash": "0915c7306e6264ba21a6cb7609b93545ccc32ef1",
"build_timestamp": "2015-02-19T12:34:48Z",
"build_snapshot": false,
"lucene_version": "4.9"
},
"tagline": "You Know, for Search"
}
```

**Comment by sckott** [comment]
agree and makes sense to only have a subset of the API avail. 

that info at root (e.g. `/cran-devel/package`) would be good and I think then would work seemlessly 

(this raises a good point - I do need to sort out a workflow for when version info isn't available)

**Comment by sckott** [comment]
ah okay, where did you get the json version info above?

**Comment by gaborcsardi** [comment]
It is the root of the ES server.

**Comment by gaborcsardi** [comment]
`http://seer.r-pkg.org:9200/` is open now.

**Comment by sckott** [comment]
thanks

**Comment by gaborcsardi** [comment]
The new server is  at http://search.r-pkg.org. FYI.
